language: node_js
node_js:
  - node
os: linux
jobs:
  include:
    - stage: test
      script: npm test
    - stage: lint
      script: npm run lint
    - stage: release
      if: type = push AND tag IS present
      install: npm ci
      script: npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: <npm-email>
        api_key:
          secure: <get-from-travis-encrypt>
        on:
          tags: true
          repo: <username>/<project>
          branch: master
stages:
  - test
  - lint
  - release
